name:                visualization-api
version:             0.2.0.0
synopsis:            Visualization API
description:         Please see README.md
homepage:            https://github.com/luna/visualization-api#readme
author:              New Byte Order
maintainer:          contact@luna-lang.org
copyright:           2016 New Byte Order

dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - lens
  - matrix
  - text

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - MultiParamTypeClasses
  - TemplateHaskell

library:
  source-dirs:      src
